app1/urls.py
app_name='app1'

from django.urls import path
from app1.views import *

urlpatterns = [
    path('page1/',page1,name='page1'),
]

app2/urls.py
app_name='app2'

from django.urls import path
from app2.views import *

urlpatterns = [
    path('page2/',page2,name='page2'),
]

project8/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

from app3.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('page3/',page3,name='page3')
]

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def page1(request):
    return render (request,"page1.html")

app2/views.py
from django.shortcuts import render

# Create your views here.

def page2(request):
    return render (request,'page2.html')

app3/views.py
from django.shortcuts import render

# Create your views here.

def page3(request):
    return render (request,'page3.html')

templates/page1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FIRST PAGE</title>
</head>
<body>
    <center>
        <h1>This is for my first page</h1>
        <h2>If u want to navigate to second page</h2>
        <h2><a href="{% url 'app2:page2' %}"><h2></h2>click here</a></h2>
    </center>
</body>
</html>

templates/page2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SECOND PAGE</title>
</head>
<body>
    <center>
        <h1>This is for my second page</h1>
        <h2>If u want to navigate to third page</h2>
        <h2><a href="{% url 'page3' %}"><h2></h2>click here</a></h2>
    </center>
</body>
</html>

templates/page3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>THIRD PAGE</title>
</head>
<body>
    <center>
        <h1>This is for my third page</h1>
        <h2>If u want to navigate to first page</h2>
        <h2><a href="{% url 'app1:page1' %}"><h2></h2>click here</a></h2>
    </center>
</body>
</html>